---
title: "Data Report"
author:
    - "Nicholas Knoblauch"
date: "`r format(Sys.time(), '%d %B, %Y')`"
params:
   rmd: "gen_data_report.Rmd"
output:
  html_document:
  highlight: tango
  number_sections: no
  theme: default
  toc: yes
  toc_depth: 3
  toc_float:
    collapsed: no
    smooth_scroll: yes
---

## RSSp results

```{r load_data,echo=F,message=F}

setwd("~/Dropbox/PolygenicRSS/code/snakemake_files/")
library(tidyverse)

rss_rdsf <- snakemake@input[["rdsf"]]

#rss_dat <- readRDS(rss_rdsf)

tparam_df <- read_df_h5(rss_rdsf,"tparam_df")  %>% group_by(tbias,tsigu) %>% do(mutate(.,replicate=as.integer(.$fgeneid)%%n())) %>% ungroup()%>% arrange(replicate) %>% mutate(rel_bias=round(tbias/tpve,2))
quh_mat <- read_2d_mat_h5(rss_rdsf,"/","quh_mat")

D <- read_vec(rss_rdsf,"D")

traitn <- snakemake@params[["traitn"]]
methn <- snakemake@params[["methn"]]
p <- unique(tparam_df$p)
n <- unique(tparam_df$n)

```

The name for this trait is `r traitn`.  It was generated by `r methn`.  There were `r p` SNPs  and `r n` individuals.


```{r}
library(ggjoy)
colnames(quh_mat) <- tparam_df$fgeneid
quh_df <- as_data_frame(quh_mat) %>% mutate(snp_id=1:n()) %>% 
  gather("fgeneid","quh",-snp_id) %>% 
  inner_join(tparam_df) 


filter(quh_df,tbias==0) %>% ggplot(aes(y=factor(round(tsigu,2)),x=quh^2,fill=factor(replicate)))+
geom_joy(panel_scaling = F)+facet_wrap(~replicate)+scale_x_log10()

quh_df <- data_frame(D=D) %>% mutate(snp_id=1:n()) %>% inner_join(quh_df)

```

```{r}
filter(quh_df,tbias==0) %>%  ggplot(aes(x=D,y=quh^2))+stat_bin_hex()+facet_wrap(~round(tsigu,2),scales = "free_y")+scale_y_log10()+scale_x_sqrt()
```

```{r}
filter(quh_df,tbias==0) %>%  ggplot(aes(sample=quh))+stat_qq()+facet_wrap(~round(tsigu,2))
```


```{r}
data_frame(D=D) %>% arrange(desc(D)) %>%mutate(rank=1:n()) %>%  ggplot(aes(x=rank,y=D))+geom_point()+scale_y_log10()
```

