---
title: "Data Report"
author:
    - "Nicholas Knoblauch"
date: "`r format(Sys.time(), '%d %B, %Y')`"
params:
   rmd: "gen_data_report.Rmd"
output:
  html_document:
  highlight: tango
  number_sections: no
  theme: default
  toc: yes
  toc_depth: 3
  toc_float:
    collapsed: no
    smooth_scroll: yes
---

## RSSp results

```{r load_data,echo=F,message=F}

setwd("~/Dropbox/PolygenicRSS/code/snakemake_files/")
library(tidyverse)
library(SeqSupport)
library(RSSp)
library(SeqArray)
# rss_rdsf <- snakemake@input[["rdsf"]]
# uh_rdsf <- snakemake@input[["uhrdsf"]]
#rss_dat <- readRDS(rss_rdsf)


geno_hf <- "~/Desktop/scratch/polyg_scratch/hdf5/sub_seq_hapmap_geno.h5"
geno_gdsf <- "~/Desktop/scratch/polyg_scratch/gds/sub_seq_hapmap_geno.gds"
yf <- "~/Desktop/scratch/polyg_scratch/RSSp_sim_gwas_pheno/sub_trait.h5"
bf <- "~/Desktop/scratch/polyg_scratch/RSSp_sim_gwas_beta/sub_beta.h5"
betamat <- t(read_2d_mat_h5(bf,"/","beta"))
ymat <- read_2d_mat_h5(yf,"trait","ymat")
gds <- seqOpen(geno_gdsf)
gdX <- seqGetData(gds,"$dosage")
gX <- t(read_2d_mat_h5(geno_hf,"/","dosage"))
all_y_pred <- gX%*%betamat
cors <- cor(all_y_pred,ymat)

all_cors <- map2_dbl(array_branch(all_y_pred,2),array_branch(ymat,2),cor)
plot(all_cors,tpdf$tpve)
tpdf <- read_df_h5(yf,"SimulationInfo")
plot(all_y_pred[,1],ymat[,1])

tparam_df <- read_df_h5(rss_rdsf,"tparam_df")  %>% group_by(tbias,tsigu) %>% do(mutate(.,replicate=as.integer(.$fgeneid)%%n())) %>% ungroup()%>% arrange(replicate) %>% mutate(rel_bias=round(tbias/tpve,2))
quh_mat <- read_2d_mat_h5(rss_rdsf,"/","quh")
uh_mat <- read_2d_mat_h5(uh_rdsf,"/","uh")

colnames(uh_mat) <- paste0("uh_",tparam_df$fgeneid)
snp_info <- read_df_h5(rss_rdsf,"snp_info")
snp_info <- mutate(snp_info,D=read_vec(rss_rdsf,"D"))
region_size <- group_by(snp_info,region_id) %>% summarise(region_size=n(),log_det=sum(log(D)),min_D=min(D),max_D=max(D),cond_num=max_D/min_D)
p <- unique(tparam_df$p)
n <- unique(tparam_df$n)

```

The name for this trait is `r traitn`.  It was generated by `r methn`.  There were `r p` SNPs  and `r n` individuals.

```{r}
library(ggjoy)
colnames(quh_mat) <- paste0(tparam_df$fgeneid)
colnames(uh_mat) <- paste0(tparam_df$fgeneid)

sim_df <- data_frame(
  quh=c(quh_mat),
  geneid=c(col(quh_mat)),
  fgeneid=tparam_df$fgeneid[geneid],
  tsigu=tparam_df$tsigu[geneid],
  tbias=tparam_df$tbias[geneid],uh_mat=c(uh_mat),
  D=D[c(row(quh_mat))],
  tvar=tsigu^2)
```


```{r}
sim_df <- group_by(sim_df,fgeneid) %>% do(mutate(.,data_var=evd_var(c(tvar[1],tbias[1]),dvec=D))) %>% ungroup
```


```{r}
ggplot(sim_df,aes(x=data_var))+geom_histogram(bins=10000)+scale_x_log10()
```


```{r}
filter(sim_df,tbias==0) %>% 
  ggplot(aes(x=quh_q,..density..))+
  geom_histogram(bins=100)+
  facet_wrap(~round(tpve,2))
```

```{r}
filter(sim_df,tbias==0) %>% ggplot(aes(sample=quh_q))+stat_qq(distribution=qunif)+facet_wrap(~round(tsigu,2))
# b_sim <- filter(sim_df,is.na(quh_q))
```


```{r}
ggplot(region_size,aes(x=region_size,y=log_det))+geom_point()+ggtitle("Determinant of LD matrices as a function of size")
```


```{r}
ggplot(region_size,aes(x=region_size,y=cond_num))+geom_point()+ggtitle("Condition number LD blocks as a function of size")
```
```{r}
ggplot(region_size,aes(x=log_det,y=cond_num))+geom_point()+ggtitle("Condition number LD blocks as a function of the determinant")
```


