---
title: "Simulation Report"
author:
    - "Nicholas Knoblauch"
date: "`r format(Sys.time(), '%d %B, %Y')`"
params:
   rmd: "gen_results_report.Rmd"
output:
  html_document:
  highlight: tango
  number_sections: no
  theme: default
  toc: yes
  toc_depth: 3
  toc_float:
    collapsed: no
    smooth_scroll: yes
---

## RSSp results

```{r load_data,echo=F,message=F}

setwd("~/Dropbox/PolygenicRSS/code/snakemake_files/")
library(tidyverse)
library(RSSp)



ldsc_gwas_resf <- snakemake@input[["ldscf"]]
rss_gwas_resf <- snakemake@input[["resf"]]
orss_gwas_resf <- snakemake@input[["oresf"]]


est_df <- read_delim(rss_gwas_resf,delim="\t") %>% 
  filter(!log_params) %>% 
  select(-log_params) %>% 
  mutate(rel_bias=round(tbias/tpve,2),
         rel_pve_error=(abs(pve-tpve)/(pve+tpve)))




est_df <- read_delim(orss_gwas_resf,delim="\t")  %>%
  inner_join(est_df) %>%
  mutate(rel_error_lnZ=abs(lnZ-oracle_lnZ)/(abs(lnZ)+abs(oracle_lnZ))) %>% mutate(fgeneid=as.character(fgeneid),method=paste0("RSSp_",method))
tparam_df<- distinct(est_df,fgeneid,tsigu,tbias,p_n,tpve)

comp_est_df <-  select(est_df,fgeneid,sigu,bias,method,p_n,pve)

ldsc_est_df <- read_delim(ldsc_gwas_resf,delim="\t") %>% mutate(fgeneid=as.character(fgeneid)) %>% inner_join(tparam_df)
comp_ldsc_est_df <- mutate(
  ldsc_est_df,
  sigu=sqrt(Total_Observed_scale_h2/p_n),
  method="LDSC"
  ) %>% select(
    pve=Total_Observed_scale_h2,
    fgeneid,
    bias=Intercept,
    sigu,
    method,
    p_n)
comp_est_df <- rbind(comp_est_df,comp_ldsc_est_df) %>% inner_join(tparam_df)
comp_est_df <- mutate(
  comp_est_df,
  t_rel_bias=round(tbias/tpve,3),
  est_rel_bias=bias/calc_pve(sigu,p_n),
  perc_tsigu=ntile(tsigu,3)
  )
# est_df <- inner_join(est_df,ldsc_est_df)
#  
#  traitn <- snakemake@params[["traitn"]]
#  methn <- snakemake@params[["methn"]]
#  p <- unique(est_df$p)
#  n <- unique(est_df$n)
```


```{r}
mutate(comp_est_df,tgrp=paste0(tpve,method)) %>% ggplot(aes(x=tpve,y=abs(pve-tpve),group=tgrp,fill=method))+
  geom_boxplot()+
  facet_wrap(~t_rel_bias,labeller=label_both)+
  ylab(bquote(RMSE[PVE]))+
  xlab(bquote(PVE))+
  scale_x_log10()
```


```{r}
filter(comp_est_df) %>% ggplot(aes(x=tpve,y=abs(pve-tpve),col=method))+
  geom_point()+geom_errorbarscale_y_log10()+
  geom_smooth(method="lm")+
  facet_grid(method~t_rel_bias,labeller=label_both)
```


