---
title: "Data Report"
author:
    - "Nicholas Knoblauch"
date: "`r format(Sys.time(), '%d %B, %Y')`"
params:
   rmd: "gen_data_report.Rmd"
output:
  html_document:
  highlight: tango
  number_sections: no
  theme: default
  toc: yes
  toc_depth: 3
  toc_float:
    collapsed: no
    smooth_scroll: yes
---

## RSSp results

```{r load_data,echo=F,message=F}

setwd("~/Dropbox/PolygenicRSS/code/snakemake_files/")
library(tidyverse)

# sim_phenof <- snakemake@input[["sim_phenof"]]
# ld_chunkf <- snakemake@input[["ldchunkf"]]
# map_uhf <- snakemake@input[["map_uhf"]]
# gen_quhf <- snakemake@input[["gen_quhf"]]
# merge_quhf <- snakemake@input[["merge_quhf"]]
# 
# all_f <- as.list(unlist(snakemake@input))

all_bench <- map_dfr(all_f,function(fn){
  read_delim(fn,delim="\t") %>% mutate(jobid=basename(fn)) %>% separate(jobid,c("trait","LDchunk","rule"),sep = "_") %>% mutate(rule=gsub(".txt","",rule),LDchunk=as.integer(LDchunk))
}
)
ggplot(all_bench,aes(x=s))+geom_histogram()+facet_wrap(~rule)

```

```{r}
group_by(all_bench,rule) %>% summarise(tot_s=sum(s)) %>% ggplot(aes(x=rule,y=tot_s))+geom_point()
```

```{r}
filter(all_bench,!is.na(LDchunk)) %>% group_by(LDchunk) %>% summarise(tot_s=sum(s)) %>% ggplot(aes(x=tot_s))+geom_histogram(bins=20)
```




