---
title: "Data Report"
author:
    - "Nicholas Knoblauch"
date: "`r format(Sys.time(), '%d %B, %Y')`"
params:
   rmd: "gen_data_report.Rmd"
output:
  html_document:
  highlight: tango
  number_sections: no
  theme: default
  toc: yes
  toc_depth: 3
  toc_float:
    collapsed: no
    smooth_scroll: yes
---

## RSSp results

```{r load_data,echo=F,message=F}

setwd("~/Dropbox/PolygenicRSS/code/snakemake_files/")
library(tidyverse)

gwas_rss_rdsf <- snakemake@input[["gwas_rdsf"]]
direct_rss_rdsf <- snakemake@input[["direct_rdsf"]]
uh_rdsf <- snakemake@input[["uhrdsf"]]

gwas_rss_dat <- readRDS(gwas_rss_rdsf)
direct_rss_dat <- readRDS(direct_rss_rdsf)


tparam_df <- gwas_rss_dat$tparam_df %>% group_by(tbias,tsigu) %>% do(mutate(.,replicate=as.integer(.$fgeneid)%%n())) %>% ungroup()%>% arrange(replicate) %>% mutate(rel_bias=round(tbias/tpve,2))

# direct_tparam_df <- direct_rss_dat$tparam_df %>% group_by(tbias,tsigu) %>% do(mutate(.,replicate=as.integer(.$fgeneid)%%n())) %>% ungroup()%>% arrange(replicate) %>% mutate(rel_bias=round(tbias/tpve,2))




quh_mat_gwas <- gwas_rss_dat$quh_mat
quh_mat_direct <- direct_rss_dat$quh_mat
uh_mat <- readRDS(uh_rdsf)[["uh_mat"]]
colnames(uh_mat) <- paste0("uh_gwas_",tparam_df$fgeneid)
D <- gwas_rss_dat$D

traitn <- snakemake@params[["traitn"]]
methn <- snakemake@params[["methn"]]
p <- unique(tparam_df$p)
n <- unique(tparam_df$n)

```

The name for this trait is `r traitn`.  It was generated by `r methn`.  There were `r p` SNPs  and `r n` individuals.


```{r}
library(ggjoy)
colnames(quh_mat_gwas) <- paste0("gwas_",tparam_df$fgeneid)
colnames(quh_mat_direct)<- paste0("direct_",tparam_df$fgeneid)
sim_df <- as_data_frame(cbind(quh_mat_direct,quh_mat_gwas)) %>% 
  mutate(snp_id=1:n()) %>% 
  gather("fgeneid","traitv",-snp_id) %>% 
  separate(fgeneid,c("type","fgeneid"))%>% 
  spread(type,traitv) %>% inner_join(tparam_df)

sim_df <- data_frame(D=D) %>% mutate(snp_id=1:n()) %>% 
  inner_join(sim_df) %>% mutate(
  true_sd=sqrt(tsigu^2*D^2+D+tbias),
  gwas_d=qnorm(gwas,mean=0,sd=true_sd),
  direct_d= qnorm(direct,mean=0,sd=true_sd)
  )


filter(sim_df,tbias==0,quh!=0) %>% mutate(tsigu=factor(round(tsigu,2)),quh_sq=quh^2)%>% ggplot(aes(y=tsigu,x=quh_sq))+
geom_joy()+scale_x_log10()


```



```{r}
distinct(sim_df,D) %>% ggplot(aes(x=D))+geom_histogram()
```


```{r}
filter(sim_df,tbias==0) %>% ggplot(aes(y=factor(round(tsigu,2)),x=uh^2))+
geom_joy()+scale_x_log10()
```

```{r}
filter(sim_df,fgeneid==1) %>% 
  ggplot(aes(x=direct_d,y=gwas_d))+stat_bin_hex()


filter(sim_df,tbias==0) %>% ggplot(aes(x=direct_d))+geom_histogram()+facet_wrap(~round(tsigu,2))

filter(sim_df,tbias==0) %>% ggplot(aes(x=gwas_d))+geom_histogram()+facet_wrap(~round(tsigu,2))


filter(sim_df,tbias==0) %>%  ggplot(aes(x=uh^2,y=quh^2))+stat_bin_hex()+facet_wrap(~round(tsigu,2),scales = "free_y")+geom_smooth(method="lm")
```



```{r}
tsim_df <- filter(sim_df,fgeneid==1)
tsim_df %>% ggplot(aes(sample=gwas))+stat_qq(distribution=qnorm,dparams=list(mean=0,sd=sqrt(tsim_df$)))
filter(sim_df,tbias==0) %>% mutate(s_sigu=round(tsigu,2))%>% ggplot(aes(sample=gwas,y=gwas))+stat_qq(distribution=qnorm,)+facet_wrap(~s_sigu)+ggtitle("uh qq_plot")
```


```{r}
filter(sim_df,tbias==0) %>% mutate(s_sigu=round(tsigu,2),rel_h=quh^2/uh^2)%>% ggplot(aes(x=rel_h,..density..))+geom_histogram(bins=1000)+facet_wrap(~s_sigu)+ggtitle("quh/uh")+scale_x_log10()
```


