import numpy as np
import gzip

def count_lines(fname):
    with gzip.open(fname) as fh:
        count = 0
        for _ in fh:
            count += 1
        return count


    

N=503
NREPS =150
PVE=list(9.999*10**np.linspace(-1,-1.5,num=4))
BIAS=[0.0]
TOT_SIM=NREPS*len(PVE)*len(BIAS)
#TOT_SIM=1
FGENEID=range(1,TOT_SIM+1)

