import numpy as np
import gzip

configpath = None
gardner_dir="../../../../../../../../group/xhe-lab/1KG/"
rcc_dir="../../../../../../../project/xinhe/eQTL/1kg/"
if os.path.exists(gardner_dir):
    configpath="../workflow_params_gardner.json"
if os.path.exists(rcc_dir):
    configpath="../workflow_params_rcc.json"
if os.path.exists("../../../../Desktop/im_xps13"):
    configpath="../workflow_params_xps.json"
if os.path.exists("../../../../Desktop/scratch"):
    configpath="../workflow_params.json"    
    
configfile:
    configpath    



def count_lines(fname):
    with gzip.open(fname) as fh:
        count = 0
        for _ in fh:
            count += 1
        return count


GWAS_NAMES = ["bd","cad","cd","ht","ra","t1d","t2d"]
GWAS_NAMES = ["t1d","t2d"]    
COMB_NAME="sscombined"
SCEN="NoConfoundSmall"
NREPS =5
PVE=list(9.999*10**np.linspace(-1,-1.5,num=4))
BIAS=[0.0]
TOT_SIM=NREPS*len(PVE)*len(BIAS)
#TOT_SIM=1
FGENEID=range(1,TOT_SIM+1)

