---
title: Results
output: html_document
---


* [Comparing RSS-p to ldsc](chr_16.html)
* [Comparing RSS-p to ldsc](chr_2.html)
* [Comparing RSS-p to ldsc](GenomeWideSimulation.html)
* [Assessing PVE using the GRM](GRM_estimation.html)
* [Background on Heritability](Heritability.html)
* [Diagonal Approximation of LD matrix](IndependenceCheck.html)
* [Meeting Notes](Meeting_Notes.html)
* [Summary of Meeting](MeetingSummary1.html)
* [Polygenic Estimation With and Without Confounding](PolygenicEstimation.html)
* [Investigating Inflation in Large Sample Simulations](RSSp_Large_Simulation.html)
* [Combined WTCC simulation results](RSSp_Large_WTCC_noConfounding.html)
* [Direct Simulation vs GWAS-style Simulation](RSSp_ldsc_gwas_direct_noConfounding.html)
* [RSSp vs ldsc (High PVE)](RSSp_ldsc_highPVE_chr1.html)
* [RSSp vs ldsc (High PVE)](RSSp_ldsc_highPVE_hr.html)
* [RSSp vs ldsc (High PVE)](RSSp_ldsc_highPVE.html)
* [RSSp vs ldsc (No Confounding)](RSSp_ldsc_noConfounding.html)
* [RSSp vs ldsc](RSSp_ldsc.html)
* [RSSp for Prediction](RSSp_Posterior.html)
* [Prediction with RSSp](RSSp_Prediction.html)
* [Deriving the Standard Error for RSSp](RSSP_standard_error.html)
* [Preliminary WTCC simulation results](RSSp_WTCC_noConfounding.html)
* [Sparse Model, Polygenic Data](RSSR_PolygenicData.html)
* [Getting up and running with LDetect](Running_ldetect.html)
* [Effect of LDshrink](shrinkage_effect.html)
* [Simulating GWAS using snakemake](simulatingGWAS.html)
* [Standardized Effect Size Simulation](simulation.html)
* [Polygenic Regression with Summary Statistics (RSSp)](Summary.html)
* [Diagnosing inflation at large sample size](RSSp_Large_Simulation.html)
