---
title: "RSSp vs ldsc"
author: "Nicholas Knoblauch"
date: 2017-11-08
output: workflowr::wflow_html
---







```{r load_data,echo=F,message=F}
library(tidyverse)
library(RSSp)
# bs2f <- "~/Dropbox/PolygenicRSS/data/Snakemake_inputs/scz2_ldsc_ex.txt"
# sigf <- "~/Desktop/scratch/polyg_scratch/gds/scz2_seq_hapmap_geno.gds"
# ldrf <- "~/Dropbox/PolygenicRSS/code/snakemake_files/scz2_LD_regions.txt"
# ldr <- scan("~/Dropbox/PolygenicRSS/code/snakemake_files/scz2_LD_regions.txt",what=integer())
# gds <- SeqArray::seqOpen(sigf)
# si <- read_SNPinfo_gds(gds,region_id = T) %>% filter(chr==1)
# nldr <- sort(unique(si$region_id))
# write(nldr,file = "~/Dropbox/PolygenicRSS/code/snakemake_files/chr1_LD_regions.txt",sep="\n")
# bs <- read_delim(bs2f,delim="\t") %>% semi_join(si)
# write_delim(bs,"~/Dropbox/PolygenicRSS/data/Snakemake_inputs/chr1_ldsc_ex.txt",delim = "\t")
ldsc_gwas_resf <- "~/Dropbox/PolygenicRSS/output/RSSp_snakemake/sim_scz2_gwas_ldsc_res.txt.gz"
rss_gwas_resf <-  "~/Dropbox/PolygenicRSS/output/RSSp_snakemake/sim_scz2_gwas_RSSp_res_ALL.txt.gz"
orss_gwas_resf <- "~/Dropbox/PolygenicRSS/output/RSSp_snakemake/sim_scz2_gwas_RSSp_oracle_res.txt.gz"


est_df <- read_delim(rss_gwas_resf,delim="\t") %>% 
  filter(!log_params,shrinkage==min(shrinkage),pv==max(pv)) %>% 
  select(-log_params) %>% 
  mutate(fgeneid=as.character(fgeneid),rel_bias=round(tbias/tpve,2),
         rel_pve_error=(abs(pve-tpve)/(pve+tpve)),method=paste0("RSSp_",method))




# est_df <- read_delim(orss_gwas_resf,delim="\t")  %>%
#   inner_join(est_df) %>%
#   mutate(rel_error_lnZ=abs(lnZ-oracle_lnZ)/(abs(lnZ)+abs(oracle_lnZ))) %>% 
#   mutate(fgeneid=as.character(fgeneid),
tparam_df<- distinct(est_df,fgeneid,tsigu,tbias,p_n,tpve)

comp_est_df <-  select(est_df,fgeneid,sigu,bias,method,p_n,pve) 

ldsc_est_df <- read_delim(ldsc_gwas_resf,delim="\t") %>% mutate(fgeneid=as.character(fgeneid)) %>% inner_join(tparam_df)
comp_ldsc_est_df <- mutate(
  ldsc_est_df,
  sigu=sqrt(Total_Observed_scale_h2/p_n),
  method="LDSC"
  ) %>% select(
    pve=Total_Observed_scale_h2,
    fgeneid,
    bias=Intercept,
    sigu,
    method,
    p_n) %>% mutate(bias=bias-1)
comp_est_df <- rbind(comp_est_df,comp_ldsc_est_df) %>% inner_join(tparam_df)
comp_est_df <- mutate(
  comp_est_df,
  t_rel_bias=round(tbias/tpve,3),
  est_rel_bias=bias/calc_pve(sigu,p_n),
  perc_tsigu=ntile(tsigu,3)
  )


```

```{r rmse_pve}
tpvev <- unique(comp_est_df$tpve)

mutate(comp_est_df,tgrp=paste0(tpve,method),relative_bias=round(tbias/tpve,4)) %>% mutate(true_pve=round(tpve,3)) %>% filter(tbias==0,tpve<0.5) %>%  ggplot(aes(x=tpve,y=abs(pve-true_pve),group=tgrp,fill=method))+
  geom_boxplot()+
  ylab(bquote(RMSE[PVE]))+xlab(bquote(PVE))+ggtitle("RMSE of PVE","No Confounding")
```
```{r joy_bias_pve}
library(ggjoy)
mutate(comp_est_df,rel_bias=round(tbias/tpve,3),true_pve=round(tpve,3)) %>% ggplot(aes(x=abs(pve-true_pve),y=method,fill=method))+geom_joy()+xlab(bquote(RMSE[PVE]))+facet_grid(true_pve~rel_bias,labeller=partial(label_both,sep="\n"))+scale_x_log10()
```
```{r joy_pve_bias}

mutate(comp_est_df,rel_bias=round(tbias/tpve,3),true_pve=round(tpve,3)) %>% ggplot(aes(x=abs(pve-true_pve),y=factor(true_pve),fill=method))+geom_joy()+xlab(bquote(RMSE[PVE]))+facet_grid(method~rel_bias,labeller=partial(label_both,sep=":\n"))+ylab(bquote(PVE))
```








```{r joy_bias_pve_rmse}
mutate(comp_est_df,rel_bias=round(tbias/tpve,3),true_pve=round(tpve,3)) %>% ggplot(aes(x=abs(pve-true_pve),y=factor(rel_bias),fill=method))+geom_joy()+xlab(bquote(RMSE[PVE]))+facet_grid(method~true_pve,labeller=partial(label_both,sep=":\n"))+ylab(bquote(frac(c,PVE)))
```

```{r pve_tpve}
mutate(comp_est_df,t_rel_bias=round(tbias/tpve,3)) %>% filter(tpve<0.2) %>% ggplot(aes(x=tpve,y=pve,color=method))+
  geom_point()+geom_smooth(method="lm")+
  facet_grid(method~t_rel_bias,labeller="label_both")+
  geom_abline(slope=1,intercept=0)+xlab(bquote(PVE))+ylab(bquote(hat(PVE)))+ggtitle("Estimated PVE vs True PVE")
```

```{r dist_pve_tpve}
mutate(comp_est_df,t_rel_bias=round(tbias/tpve,3),true_pve=round(tpve,3)) %>%filter(true_pve<0.2) %>% ggplot(aes(x=t_rel_bias,y=tpve-pve,color=method))+
  geom_point()+geom_smooth(method="lm")+
  facet_grid(method~true_pve,labeller="label_both")+geom_hline(yintercept = 0)+
  xlab(bquote(frac(c,PVE)))+ylab(bquote(PVE-hat(PVE)))+ggtitle("RMSE of PVE as a function of relative confounding")
```


```{r est_pve_tpve_zoom}
filter(comp_est_df,method!="RSSp_NoConfound") %>% mutate(relative_bias=round(tbias/tpve,3)) %>% ggplot(aes(x=tpve,y=pve,color=method))+
  geom_point()+geom_smooth(method="lm")+
  facet_grid(method~relative_bias,labeller="label_both")+
  geom_abline(slope=1,intercept=0)+xlab(bquote(PVE))+ylab(bquote(hat(PVE)))+ggtitle("Estimated PVE vs True PVE")
```

```{r est_pve_tpve_method}
filter(comp_est_df,method!="RSSp_NoConfound") %>% mutate(t_rel_bias=round(tbias/tpve,3),true_pve=round(tpve,3)) %>% ggplot(aes(x=tbias/tpve,y=bias/tpve,color=method))+
  geom_point()+geom_smooth(method="lm")+
  facet_grid(true_pve~method,labeller=partial(label_both,sep=":\n"),scales = "free_y")+
  geom_abline(slope=1,intercept=0)+xlab(bquote(frac(c,PVE)))+ylab(bquote(frac(hat(c),PVE)))+ggtitle("Estimated Relative Confounding")
```









