---
title: "RSSp for Prediction"
author: "Nicholas Knoblauch"
date: 2017-10-20
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

<!-- Add your analysis here -->

## Deriving the RSSp Posterior ##

$$ \textbf{u} \sim N(0,I_p\sigma^2_u)$$
$$\hat{\textbf{u}}|\textbf{u} \sim N(R\textbf{u},R+cI_p)$$
From Bishop's, _Pattern Recognotion and Machine Learning_ we get
$$ \hat{\textbf{u}} \sim N(0,\sigma_u^2R^2+R+cI_p)$$

as well as the posterior

$$ \textbf{u} \sim N(\Sigma R  (R+cI_p)^{-1}\hat{\textbf{u}},\Sigma)$$
Where $$\Sigma = (\frac{1}{\sigma^2_u} I_p +R (R+cI_p)^{-1}R)^{-1}$$


Given the EVD of R, $R=QDQ^{T}$, Let's denote $D^\dagger=D+cI_p$, this means that $(R+cI_p)^{-1}= (QDQ^{T}+cIp)^{-1}=QD^{\dagger^{-1}}Q^{T}$.  We can repeat this trick to simplify $\Sigma$ further, ending up with 
$$\Sigma=QD^{\dagger\dagger^{-1}}Q^{T}$$ where
$$D^{\dagger\dagger}=\frac{1}{\sigma_u^2}I_p+ D^{\dagger^{-1}}=\text{diag}(\frac{1}{\lambda+c}+\frac{1}{\sigma_u^2})$$
Simplifying further:

$$\textbf{u} \sim N(Q D^{\dagger \dagger^{-1}} Q^{T}QDQ^{T}QD^{\dagger^{-1}}Q^{T}\hat{\textbf{u}},QD^{\dagger \dagger^{-1}}Q^{T})$$
$$ \Rightarrow N(QD^{\dagger \dagger^{-1}} D D^{\dagger^{-1}}Q^{T},QD^{\dagger\dagger^{-1}}Q^{T})  $$
$$\Rightarrow N(QD^{\dagger \dagger \dagger}Q^{T}\hat{\textbf{u}},QD^{\dagger \dagger^{-1}}Q^{T})$$

with $$D^{\dagger \dagger \dagger} = D^{\dagger \dagger^{-1}} D D^{\dagger^{-1}} =\text{diag}(\frac{\sigma_u^2(c+\lambda)}{c+\lambda+ \sigma_u^2} \times \lambda \times \frac{1}{\lambda+c}) = \text{diag}(\frac{\lambda \sigma^2_u}{c+\lambda+\sigma_u^2})$$







## Session information




<!-- Insert the session information into the document -->
```{r session-info}
```
